#!/usr/bin/env bash
# Extract SAP NW RFC SDK and configure SAPNWRFC_HOME for PyRFC.
#
# Official source (requires S-user):
#   https://support.sap.com/en/product/connectors/nwrfcsdk.html
#
# Community mirror (dev only; verify license with your SAP basis team):
#   https://github.com/juanmoura/nwrfcsdk
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SDK_DIR="${ROOT}/lib/nwrfcsdk"
GITHUB_REPO="${NWRFCSDK_GITHUB_REPO:-https://github.com/juanmoura/nwrfcsdk.git}"

# DevSidecar proxy (see https://github.com/docmirror/dev-sidecar)
DEV_SIDECAR_HTTP_PROXY="${DEV_SIDECAR_HTTP_PROXY:-${DS_HTTP_PROXY:-http://127.0.0.1:31180}}"
DEV_SIDECAR_HTTPS_PROXY="${DEV_SIDECAR_HTTPS_PROXY:-${DS_HTTPS_PROXY:-http://127.0.0.1:31181}}"

usage() {
  cat <<EOF
Usage:
  ./install-nwrfcsdk.sh <nwrfcsdk-archive-or-directory>
  ./install-nwrfcsdk.sh --from-github

Sources:
  - Local archive: nwrfcsdk-*.zip / .tar.gz from SAP Software Center
  - Local directory with lib/ and include/
  - --from-github: clone ${GITHUB_REPO} (uses DevSidecar proxy when reachable)

DevSidecar proxy (optional, speeds up GitHub in CN):
  DEV_SIDECAR_HTTP_PROXY=${DEV_SIDECAR_HTTP_PROXY}
  DEV_SIDECAR_HTTPS_PROXY=${DEV_SIDECAR_HTTPS_PROXY}

After install:
  cat .env.local-sdk >> .env
  source .venv/bin/activate
  export SAPNWRFC_HOME=${SDK_DIR}
  export LD_LIBRARY_PATH=${SDK_DIR}/lib:\${LD_LIBRARY_PATH:-}
  pip install pyrfc
  ./start.sh
EOF
}

sidecar_proxy_reachable() {
  curl -sS --max-time 2 -x "$DEV_SIDECAR_HTTPS_PROXY" -o /dev/null https://github.com 2>/dev/null
}

git_with_proxy() {
  if sidecar_proxy_reachable; then
    echo "Using DevSidecar proxy: ${DEV_SIDECAR_HTTPS_PROXY}" >&2
    git \
      -c http.proxy="$DEV_SIDECAR_HTTP_PROXY" \
      -c https.proxy="$DEV_SIDECAR_HTTPS_PROXY" \
      "$@"
  else
    echo "DevSidecar proxy not reachable; cloning directly." >&2
    git -c http.proxy= -c https.proxy= "$@"
  fi
}

clone_from_github() {
  local workdir
  workdir="$(mktemp -d)"
  trap 'rm -rf "$workdir"' RETURN
  echo "Cloning ${GITHUB_REPO} ..."
  git_with_proxy clone --depth 1 "$GITHUB_REPO" "$workdir/repo"
  install_sdk_root "$workdir/repo"
}

find_sdk_root() {
  local base="$1"
  if [[ -d "${base}/lib" && -d "${base}/include" ]]; then
    echo "$base"
    return 0
  fi
  local candidate
  while IFS= read -r candidate; do
    if [[ -d "${candidate}/lib" && -d "${candidate}/include" ]]; then
      echo "$candidate"
      return 0
    fi
  done < <(find "$base" -mindepth 1 -maxdepth 3 -type d 2>/dev/null)
  return 1
}

install_sdk_root() {
  local src="$1"
  local sdk_root
  sdk_root="$(find_sdk_root "$src")" || {
    echo "Could not locate NW RFC SDK root (expected lib/ and include/ subdirs)." >&2
    exit 1
  }

  rm -rf "$SDK_DIR"
  mkdir -p "$(dirname "$SDK_DIR")"
  cp -a "$sdk_root" "$SDK_DIR"

  cat >"${ROOT}/.env.local-sdk" <<EOF
# Generated by install-nwrfcsdk.sh — append or merge into .env
SAPNWRFC_HOME=${SDK_DIR}
EOF

  echo "Installed NW RFC SDK to: ${SDK_DIR}"
  echo "Wrote ${ROOT}/.env.local-sdk"
  echo ""
  echo "Next steps:"
  echo "  cat .env.local-sdk >> .env"
  echo "  export SAPNWRFC_HOME=${SDK_DIR}"
  echo "  export LD_LIBRARY_PATH=${SDK_DIR}/lib:\${LD_LIBRARY_PATH:-}"
  echo "  source .venv/bin/activate && pip install pyrfc"
}

install_from_path() {
  local archive="$1"
  local workdir
  workdir="$(mktemp -d)"
  trap 'rm -rf "$workdir"' RETURN

  mkdir -p "${ROOT}/lib"

  if [[ -d "$archive" ]]; then
    install_sdk_root "$archive"
    return 0
  fi

  echo "Extracting $archive ..."
  case "$archive" in
    *.zip) unzip -q "$archive" -d "$workdir" ;;
    *.tar.gz | *.tgz) tar -xzf "$archive" -C "$workdir" ;;
    *.tar) tar -xf "$archive" -C "$workdir" ;;
    *)
      echo "Unsupported archive format: $archive" >&2
      exit 1
      ;;
  esac
  install_sdk_root "$workdir"
}

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

case "$1" in
  -h | --help | help)
    usage
    exit 0
    ;;
  --from-github | github)
    clone_from_github
    ;;
  *)
    install_from_path "$1"
    ;;
esac
